# Site settings
title: Yinghua Guan - Full Stack Data Scientist
description: "A blog about Yinghua Guan ..."
baseurl: "/yinghuaguan.github.io" # for test: remove string '/space-jekyll-template' to ''
url: "http://yinghuaguan.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: 🤓Yinghua Guan💻
user_title: 🤓Yinghua Guan💻
email: yinghuaguan.ca@gmail.com

github_username:  yinghuaguan
linkedin_public_url: yinghuaguan # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: yinghuaguan
profile_picture: https://media.licdn.com/dms/image/C4D03AQEShV4QicuCaA/profile-displayphoto-shrink_200_200/0?e=1575504000&v=beta&t=w8gcZDSGDcP_CA1J2d6hXbSkB5kg_XOuKDKEhuDSumI

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: tags
      url: /tags
      key_trigger: 3
    - title: about me
      url: /about
      key_trigger: 4
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Text-Similarity-Detector-API
    url: https://github.com/yinghuaguan/portfolio/tree/master/NLP_projects/Text-Similarity-Detector-API
  - name: Landmark-Detection-Tracking
    url: https://github.com/yinghuaguan/portfolio/tree/master/Computer_Vision_Projects/P3_Landmark_Detection_Tracking
  - name: BlackBox-Python
    url: https://github.com/yinghuaguan/portfolio/tree/master/open_source_development/BlackBox_Python

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
